### ISSUE TITLE
stopping_strings not working for me

### ISSUE THREAD

**Issue by danpizzy** [oobabooga/text-generation-webui#1431]
### Describe the bug

ive tried using     'stopping_strings': ["Human"],
 on the vicuna model and it doesnt work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

using the api

### Logs

```shell
### Human: Create a list of H1 headings for this article
### Assistant: 1. Introduction to StoryAI
2. The Unique Selling Point of StoryAI
3. In-Depth Description of StoryAI
4. Top Features of StoryAI
```

### System Info

```shell
google colab api with  linux
```

**Comment by karlovm** [comment]
I've already fixed this bug. It's on PR now

**Comment by CyberTimon** [comment]
> I've already fixed this bug. It's on PR now

I've tried this but it still doesn't stop. Are you sure this works with the latest commit?

**Comment by schauppi** [comment]
Do not work for me either.

**Comment by KennyVaneetvelde** [comment]
Same here though, testing out some different formats for actor prompts like this example:

```
### Human: "How many people live in the United States as of 2023?"
### Assistant: @THOUGHT: ["To find out how many people live in the United States in 2023, I must perform a search."]
@SEARCH: ["United States population data 2023"]
@OBSERVE: ["The United States of America (U.S.A. or USA), commonly known as the United States (U.S. or US) or America, is a country primarily located in North America. It consists of 50 states, a federal district, five major unincorporated territories, nine Minor Outlying Islands,[i] and 326 Indian reservations."]
@THOUGHT: ["This result does not contain the information I am looking for. I will try the second result.
@SEARCH: ["United States population data 2023"]
@OBSERVE: ["The current population of the United States of America is 336,533,810 as of Friday, May 12, 2023, based on Worldometer elaboration of the latest United Nations data.
The United States 2020 population is estimated at 331,002,651 people at mid year according to UN data."]
```

However even after adding this in my stopping strings is not working no matter the variation I try, with colons, without, with spaces, without, ... It's not stopping and will hallucinate the OBSERVE part (and all subsequent conversation until it is turn for the human to act again, it does stop there)
`'\n@SEARCH:', '\n@OBSERVE:', '\n@ANSWER:'`
