### ISSUE TITLE
Packages error after update

### ISSUE THREAD

**Issue by Koronos** [oobabooga/text-generation-webui#3860]
### Describe the bug

Today, I update using the update_wsl script, but I got the error below (see logs section).
I tried to do a fresh install, (purging the pip cache) but I got the same error. It works before the update.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to make a fresh install using WSL installed with Nvidia

### Logs

```shell
Traceback (most recent call last):
  File "/root/text-gen-install/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/pydantic/fields.py)
```
```


### System Info

```shell
Windows 11
Ubuntu WSL 2 20.04.6 LTS
Nvidia 4080
```

**Comment by Slug-Cat** [comment]
I am also getting this, though I pulled yesterday

**Comment by oobabooga** [comment]
Should be fixed after https://github.com/oobabooga/text-generation-webui/commit/66d5caba1b79b060ca1a5626d9c958711ba1e3b6

**Comment by Koronos** [comment]
Thanks for your reply, but the error persist after update or a fresh install:

```
Traceback (most recent call last):
  File "/root/text-gen-install/text-generation-webui/server.py", line 12, in <module>
    import gradio as gr
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/root/text-gen-install/installer_files/env/lib/python3.10/site-packages/pydantic/fields.py)
```

**Comment by bparrott78** [comment]
I was able to fix it by going into \text-generation-webui and running pip install -r requirements.txt again

**Comment by oobabooga** [comment]
See https://github.com/oobabooga/text-generation-webui/issues/3874 for the solution.
