### ISSUE TITLE
ImportError: Using IPEX but IPEX is not installed

### ISSUE THREAD

**Issue by Naozumi520** [oobabooga/text-generation-webui#4447]
### Describe the bug

ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fine tuning

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/52615455/e4f52c0e-61a8-4385-b8be-626b92a642fe)

### Logs

```shell
2023-11-02 22:50:14 INFO:Loading PygmalionAI_pygmalion-2-7b...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.82s/it]
2023-11-02 22:50:22 INFO:Loaded the model in 7.78 seconds.
2023-11-02 22:50:36 INFO:Loading JSON datasets...
Map: 100%|██████████████████████████████████████████████████████████████| 22102/22102 [00:11<00:00, 1989.12 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 586/586 [00:00<00:00, 2067.24 examples/s]
2023-11-02 22:50:50 INFO:Getting model ready...
2023-11-02 22:50:51 INFO:Preparing for training...
2023-11-02 22:50:51 INFO:Creating LoRA model...
2023-11-02 22:50:59 INFO:Starting training...
Training 'llama' model using (q, v) projections
Trainable params: 16,777,216 (0.2484 %), All params: 6,755,192,832 (Model: 6,738,415,616)
2023-11-02 22:50:59 INFO:Log file 'train_dataset_sample.json' created in the 'logs' directory.
Exception in thread Thread-7 (threaded_run):
Traceback (most recent call last):
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\modules\training.py", line 696, in threaded_run
    trainer.train()
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1591, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1707, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1360, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Naozu\Downloads\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\trainer.py", line 1336, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.
2023-11-02 22:50:59 INFO:Training complete, saving...
2023-11-02 22:50:59 INFO:Training complete!
```
```


### System Info

```shell
OS: Windows 11 Version 10.0.22621.2428
GPU: RTX 4090
```

**Comment by x0rb0t** [comment]
I had same issue, but fixed it by installing Intel® Extension for PyTorch
`python -m pip install intel_extension_for_pytorch`
Check here: https://github.com/intel/intel-extension-for-pytorch

**Comment by Naozumi520** [comment]
I see, but why I need that intel ipex? I'm using nvidia cards.

**Comment by jpajak** [comment]
Getting the same error, and installing the extension doesn't fix it for me. - on both Windows and WSL

**Comment by x0rb0t** [comment]
> I see, but why I need that intel ipex? I'm using nvidia cards.

Because it seems that:

`trainer = transformers.Trainer(
        model=lora_model,
        train_dataset=train_data,
        eval_dataset=eval_data,
        args=transformers.TrainingArguments(
            ...
            use_ipex=True if is_torch_xpu_available and not shared.args.cpu else False 
        ),`

"use_ipex=True" in your case, and it performs some intel optimizations on the model in the 'huggingface/transformers' library.
"self.ipex_optimize_model" requires "import intel_extension_for_pytorch as ipex" to work.

Not sure if it makes any effect when launched on GPU.

**Comment by x0rb0t** [comment]
> Getting the same error, and installing the extension doesn't fix it for me. - on both Windows and WSL

Check if you installed intel_extension_for_pytorch under correct conda environment.

**Comment by jpajak** [comment]
> > Getting the same error, and installing the extension doesn't fix it for me. - on both Windows and WSL
> 
> Check if you installed intel_extension_for_pytorch under correct conda environment.

Apparently not - thanks, that worked.

**Comment by DartPower** [comment]
Too have this problem. Can't use train LoRA on ANY model.

![image](https://github.com/oobabooga/text-generation-webui/assets/2005369/2af596bc-7436-43ca-b20d-2ed58365db86)
![image](https://github.com/oobabooga/text-generation-webui/assets/2005369/43b0c84d-7af2-4a70-9371-ac71d60265ca)

Using CUDA 11
GPU: RTX 2060S

**Comment by juanps90** [comment]
For anyone still wasting time with this, update modules/training.py and set use_ipex = False.

**Comment by witnesse1920** [comment]
I updated modules/training.py but the IPEX error is not improved. we are using cu12.1, do we need to downgrade?

**Comment by PGadoury** [comment]
I would suggest that until they release a windows distribution of ipex for pytorch, the code sets use_ipex to false. It seems pretty cludgy to have to manually set this to false.

**Comment by Urammar** [comment]
> For anyone still wasting time with this, update modules/training.py and set use_ipex = False.

This doesn't even work for me.

**Comment by danucalovj** [comment]
Any updates on this issue? Training is completely unusable. I'm running into the same issue on Linux running on runpod.io on a ubuntu based image with pytorch 2.1. Already tried the workaround here and in #4570 and still getting the error related to IPEX:

Exception in thread Thread-23 (threaded_run):
Traceback (most recent call last):
  File "/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/text-generation-webui/installer_files/env/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/text-generation-webui/modules/training.py", line 696, in threaded_run
    log_train_dataset(trainer)
    ^^^^^^^^^^^^^^^
  File "/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1655, in _inner_training_loop
    model = self._wrap_model(self.model_wrapped)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1315, in _wrap_model
    model = self.ipex_optimize_model(model, training, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/text-generation-webui/installer_files/env/lib/python3.11/site-packages/transformers/trainer.py", line 1291, in ipex_optimize_model
    raise ImportError(
ImportError: Using IPEX but IPEX is not installed or IPEX's version does not match current PyTorch, please refer to https://github.com/intel/intel-extension-for-pytorch.

@oobabooga

**Comment by AstrisCantCode** [comment]
Fixed as of PR https://github.com/oobabooga/text-generation-webui/pull/5161. The function that determines if IPEX is available was being interpreted as a boolean itself, rather than being called.

**Comment by Rizwanali324** [comment]
@moritzschaefer 
im still facing this while using kaggle cpu
