### ISSUE TITLE
Instruction Template Loader is Broke Bad

### ISSUE THREAD

**Issue by Remowylliams** [oobabooga/text-generation-webui#5118]
### Describe the bug

While writing a updated ChatML prompt. I saved it as a new yaml file, then hit the dropdown reload button.
Life was not good after that. 
The new file saved but without the custom system message saved. Maybe that's alright and I have to manually wedge it into the instruction template.
However once I click the dropdown reload, any attempt to load any template gives a error.
I have to restart TGW to get a dropdown list I can use again.
Without hitting the dropdown reload button I can change between templates fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start TGW, go to parameters->Instruction Template
Select a template
Load the template
Hit the dropdown reload button
Change template
Click load

### Screenshot

![OobaBooga_InstructTemplate](https://github.com/oobabooga/text-generation-webui/assets/6888434/baa53545-0641-4603-bcb3-a7cd480572a4)

### Logs

```shell
Traceback (most recent call last):
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 241, in postprocess
    self._warn_if_invalid_choice(y)
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 229, in _warn_if_invalid_choice
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/ai_goodies/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                                  ^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

### System Info

```shell
Commit: 3fd707380868ad6a2ba57aaed4c96799c2441d99

Linux 22.04, dual Nvidia RTX 3090, 128GB Ram Python 3.11.5
```

**Comment by melroy89** [comment]
Same problem. 100% reproducible:

![image](https://github.com/oobabooga/text-generation-webui/assets/628926/9bf73650-5914-4a0c-8bc1-a234953e7431)

```
                                                  ^^^^^^^^
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 241, in postprocess
    self._warn_if_invalid_choice(y)
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 229, in _warn_if_invalid_choice
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melden/text-generation-webui/installer_files/env/lib/python3.11/site-packages/gradio/components/dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                                  ^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by TheRealMiRRoRMaN** [comment]
[mamei16] /r/ you stay out of my way, like forever. don't close any more of my threads and don't remove my ability to ask something, janny. thank you.

**Comment by mamei16** [comment]
I am confident to have found the problem, however it appears @oobabooga is unable to reproduce this issue on his end :confused: Can anybody having this issue try out [my proposed fix](https://github.com/oobabooga/text-generation-webui/compare/main...mamei16:text-generation-webui:fix_instruction_templates_refresh) and report back?

**Comment by TheRealMiRRoRMaN** [comment]
> I am confident to have found the problem, however it appears @oobabooga is unable to reproduce this issue on his end 😕 Can anybody having this issue try out [my proposed fix](https://github.com/oobabooga/text-generation-webui/compare/main...mamei16:text-generation-webui:fix_instruction_templates_refresh) and report back?

so you basically admitted that:

1. i did have a real problem.
2. you had no reason to close my thread, what so ever.
3. you banned me from that extension area from opening threads for no reason.
4. you're a bad mod with an itchy trigger finger.
5. you should have just given it time, and you need to re-open my thread and give my access back.

**Comment by TheRealMiRRoRMaN** [comment]
just delete my comments really? did you give my access back yet to that other repository? i mean where else am i supposed to ask this?

**Comment by TheRealMiRRoRMaN** [comment]
huge surprise but your "confiden fix" doesn't work, sport.

**Comment by Remowylliams** [comment]
So is this a situation where I have to wipe TGW and reinstall since Oobabooga isn't seeing this failure?

**Comment by verdelyi** [comment]
TBH even if I wipe and reinstall it doesn't work. The reload button really messes it up, and even without that, I think chat-instruct mode is broken, as it gives a basically empty prompt to the model.

**Comment by verdelyi** [comment]
The latest update seems to have fixed the error message, but I still think the Metharme template is broken (see #5225)

**Comment by melroy89** [comment]
> just delete my comments really? did you give my access back yet to that other repository? i mean where else am i supposed to ask this?

did he? I unstarred the project.

**Comment by mamei16** [comment]
> > just delete my comments really? did you give my access back yet to that other repository? i mean where else am i supposed to ask this?
> 
> did he? I unstarred the project.

Yes he did. I gave the project a star to even things out. The original problem described in this issue should be fixed by my commit [bec4e0a](https://github.com/oobabooga/text-generation-webui/commit/bec4e0a1cee50bfd5d08783970179a2a4e302bd4).

**Comment by TheRealMiRRoRMaN** [comment]
> > > just delete my comments really? did you give my access back yet to that other repository? i mean where else am i supposed to ask this?
> > 
> > 
> > did he? I unstarred the project.
> 
> Yes he did. I gave the project a star to even things out. The original problem described in this issue should be fixed by my commit [bec4e0a](https://github.com/oobabooga/text-generation-webui/commit/bec4e0a1cee50bfd5d08783970179a2a4e302bd4).

"should" being the operative word here. it doesn't fix it though.

but hey, what do I know. I only been programming since 1988.

**Comment by Remowylliams** [comment]
Updating to https://github.com/oobabooga/text-generation-webui/commit/bec4e0a1cee50bfd5d08783970179a2a4e302bd4 Seems to fix the problem. Thanks very much
