### ISSUE TITLE
Unable to load any gguf model

### ISSUE THREAD

**Issue by Touch-Night** [oobabooga/text-generation-webui#6415]
### Describe the bug

The latest dev branch is not able to load any gguf models, with either llama.cpp or llamacpp_hf loader.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a gguf model with llama.cpp or llamacpp_hf loader and see the error.

### Logs

```shell
16:38:30-935548 INFO     Loading "9b-gemma-2-Ifable-9B.Q4_K_M.gguf"
16:38:31-315766 INFO     llama.cpp weights detected: "models\9b-gemma-2-Ifable-9B.Q4_K_M.gguf"
16:38:31-420351 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "E:\tgwdev\text-generation-webui\modules\ui_model_menu.py", line 231, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tgwdev\text-generation-webui\modules\models.py", line 93, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tgwdev\text-generation-webui\modules\models.py", line 278, in llamacpp_loader
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tgwdev\text-generation-webui\modules\llamacpp_model.py", line 85, in from_pretrained
    result.model = Llama(**params)
                   ^^^^^^^^^^^^^^^
  File "E:\tgwdev\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\llama.py", line 369, in __init__
    internals.LlamaModel(
  File "E:\tgwdev\text-generation-webui\installer_files\env\Lib\site-packages\llama_cpp_cuda\_internals.py", line 51, in __init__
    model = llama_cpp.llama_load_model_from_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 2: TypeError: expected llama_model_params instance instead of llama_model_params

Exception ignored in: <function LlamaCppModel.__del__ at 0x00000218C9C45E40>
Traceback (most recent call last):
  File "E:\tgwdev\text-generation-webui\modules\llamacpp_model.py", line 33, in __del__
    del self.model
        ^^^^^^^^^^
AttributeError: 'LlamaCppModel' object has no attribute 'model'
```

### System Info

```shell
Not necessary.
```

**Comment by Touch-Night** [comment]
Tried on llama_cpp_python 0.3.0 and 0.3.1

**Comment by Touch-Night** [comment]
It is llama_cpp_python's issue.

**Comment by Touch-Night** [comment]
So downgrade llama_cpp_python to 0.2.90 if you encountered this issue until it's fixed.

**Comment by ProfessorVoodoo** [comment]
I've encountered the same problem, how were you able to downgrade llama_cpp_python to a previous version?

**Comment by Touch-Night** [comment]
Edit the requirements files and then use update wizard.

**Comment by oobabooga** [comment]
I'm trying to fix it

https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/commits/main/

**Comment by Touch-Night** [comment]
Build almost done

**Comment by Touch-Night** [comment]
Fixed

**Comment by B0rner** [comment]
I'm still having that error ( `AttributeError: 'LlamaCppModel' object has no attribute 'model'`) if I'm trying to load gemma2 gguf file ( `gemma-2-9b-it-Q4_K_L.gguf`). But loading a llama3 gguf file works fine.

Is there a way to determine the current version of text-generation-webui, that I'm using?

I did a `git pull origin main` and a ` followed by `pip install --upgrade -r requirements.txt` so I think, I have the actual release, right?

I'm using python 3.11 on windows. Any idea waht is goning wrong?
